<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('/datasets/insurance.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
Пол                  5000 non-null int64
Возраст              5000 non-null float64
Зарплата             5000 non-null float64
Члены семьи          5000 non-null int64
Страховые выплаты    5000 non-null int64
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [4]:
data.head(10)

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0
5    1     43.0   41000.0            2                  1
6    1     39.0   39700.0            2                  0
7    1     25.0   38600.0            4                  0
8    1     36.0   49700.0            1                  0
9    1     32.0   51700.0            1                  0

In [5]:
data.isna().sum()

Пол                  0
Возраст              0
Зарплата             0
Члены семьи          0
Страховые выплаты    0
dtype: int64

Дубликаты искать не вижу смысла, так как нет идентификатора и одинаковые значения у разных людей могут легко повторяться.

In [6]:
data[['Возраст','Зарплата']] = data[['Возраст','Зарплата']].astype('int64')

In [7]:
data.describe()

Пол      Возраст      Зарплата  Члены семьи  Страховые выплаты
count  5000.000000  5000.000000   5000.000000  5000.000000        5000.000000
mean      0.499000    30.952800  39916.359400     1.194200           0.148000
std       0.500049     8.440807   9900.082063     1.091387           0.463183
min       0.000000    18.000000   5300.000000     0.000000           0.000000
25%       0.000000    24.000000  33300.000000     0.000000           0.000000
50%       0.000000    30.000000  40200.000000     1.000000           0.000000
75%       1.000000    37.000000  46600.000000     2.000000           0.000000
max       1.000000    65.000000  79000.000000     6.000000           5.000000

In [8]:
features = data.drop('Страховые выплаты', axis=1)
target = data['Страховые выплаты']

In [9]:
ndata = np.array(features)

In [10]:
ndata.shape

(5000, 4)

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** Прогноз не изменится. Поменяются только веса.

**Обоснование:** 
Лучше сначала преобразовать саму формулу<br>
$$
w = (X^T X)^{-1} X^T y = X^{-1} y
$$
<br>
$$
w(P) = ((XP)^T XP)^{-1} (XP)^T y = ((XP)^T)^{-1} * (XP)^{-1} * (XP)^T y = E * P^{-1} * X^{-1} y = P^{-1} * w
$$

## Алгоритм преобразования

In [11]:
x = ndata
y = target
w = np.linalg.inv((x.T @ x)).dot(x.T).dot(y)
print(w)

[-4.43854736e-02  2.33356252e-02 -1.17739062e-05 -4.55168115e-02]


In [12]:
model = LinearRegression()
model.fit(ndata, y)
predictions = model.predict(ndata)
r2_score(y, predictions)

0.42494550308169177

Создаем обратимую матрицу.

In [13]:
z = np.random.randint(0, 10, size=(4, 4))
z

array([[4, 0, 6, 7],
       [1, 3, 6, 7],
       [0, 9, 9, 3],
       [3, 5, 4, 7]])

In [14]:
zinv = np.linalg.inv(z)
zinv

array([[ 0.23404255, -0.41489362,  0.04964539,  0.15957447],
       [-0.09929078, -0.08156028,  0.04964539,  0.15957447],
       [ 0.13475177,  0.0035461 ,  0.09929078, -0.18085106],
       [-0.10638298,  0.23404255, -0.11347518,  0.06382979]])

In [15]:
z @ zinv

array([[ 1.00000000e+00,  0.00000000e+00,  5.55111512e-17,
        -6.93889390e-17],
       [ 6.93889390e-17,  1.00000000e+00,  5.55111512e-17,
        -1.80411242e-16],
       [ 1.38777878e-17,  1.11022302e-16,  1.00000000e+00,
        -3.19189120e-16],
       [ 6.93889390e-17,  0.00000000e+00,  5.55111512e-17,
         1.00000000e+00]])

Единичную получили, хорошо.

In [16]:
f = ndata @ zinv
f

array([[ 6679.74468085,   172.36170213,  4926.79432624, -8963.44680851],
       [ 5115.89361702,   131.23404255,  3775.21985816, -6864.93617021],
       [ 2826.90780142,    72.10283688,  2086.54609929, -3793.24468085],
       ...,
       [ 4565.88652482,   119.04964539,  3366.72340426, -6127.53191489],
       [ 4404.11347518,   114.45035461,  3247.60992908, -5909.96808511],
       [ 5468.26950355,   141.5070922 ,  4032.53191489, -7337.86170213]])

In [17]:
model.fit(f, y)
predictions = model.predict(f)
r2_score(y, predictions)

0.4249455030816869

Качество совпадает.